### ISSUE TITLE
error permission.WRITE_SETTINGS

### ISSUE THREAD

**Issue by ralite** [Hiraqui/cordova-plugin-ringtone#5]
Hi, 

I try tu use your plugin, but I have an error : Error settings as alarmcom.ionicframework.myproject was not granted this permession.WRITE_SETTINGS

Can you help me ?

thank

**Comment by mugenyi** [comment]
did you solve the problem i am also getting it

**Comment by Hiraqui** [comment]
Hi,
This issue happens on sdk 23, Android 6.0 because global permission is not allowed for WRITE_SETTINGS.
There are two solutions: 
- Restrict sdk to 22 or lower
- Use https://github.com/dpa99c/cordova-diagnostic-plugin to prompt app permission before using this plugin

More about this in Ionic forum:
https://forum.ionicframework.com/t/android-6-0-not-request-contact-permission/46600/7
